name: release-docker-images

# on:
#   push:
#     tags:
#       - '*'

on:
  pull_request:
    branches:
      - main

env:
  IMAGE: zappi/vllm-openai
  VLLM_VERSION: 0.9.2
  TRITON_VERSION: 3.2.0

jobs:
  docker-hub-release:
    runs-on: ubuntu-latest
    steps:
      - name: Free additional disk space
        run: |
          df -h
          echo "Removing android..."
          sudo rm -rf /usr/local/lib/android
          echo "Removing dotnet..."
          sudo rm -rf /usr/share/dotnet
          echo "Removing haskell"
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          echo "Removing tool cache..."
          sudo rm -rf /opt/hostedtoolcache
          df -h
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ env.VLLM_VERSION }}-triton-${{ env.TRITON_VERSION }}
            type=raw,value=${{ env.VLLM_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build, tag, and push image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VLLM_VERSION=${{ env.VLLM_VERSION }}
            TRITON_VERSION=${{ env.TRITON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}


  # github-release:
  #   runs-on: ubuntu-latest
  #   needs: docker-hub-release-manifest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5
  #     - name: Create Release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Version ${{ github.ref }}
  #         draft: false
  #         prerelease: false
