name: test-docker-image

on:
  pull_request:
    branches:
      - main

env:
  IMAGE: zappi/vllm-openai

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare additional disk space
        run: |
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          rm -rf /opt/hostedtoolcache
          df -h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test building of image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.amd64
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare additional disk space
        run: |
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          rm -rf /opt/hostedtoolcache
          df -h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test building of image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.arm64
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/arm64
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
