name: test-docker-image

on:
  pull_request:
    branches:
      - main

env:
  IMAGE: zappi/vllm-openai

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    concurrency: amd64
    steps:
      - name: Free additional disk space
        run: |
          df -h
          rm -rf /opt/hostedtoolcache/
          df -h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test building of image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.amd64
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          push: false
          tags: ${{ steps.metadata.outputs.tags }}

  build-arm64:
    runs-on: ubuntu-latest
    concurrency: arm64
    steps:
      - name: Free additional disk space
        run: |
          df -h
          rm -rf /opt/hostedtoolcache/
          df -h
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test building of image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.arm64
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/arm64
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
